package hibernateorm;
// Generated Oct 20, 2020 12:18:33 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */

import javax.faces.bean.ManagedBean;
import Dao.Dao;
import java.util.List;
@ManagedBean(name = "student")

public class Student  implements java.io.Serializable {


     private int id;
     private String name;
     private String department;
     private String division;
     public String errorMessage;
     public List<Student> ketua;
     public List<Student> sekre1;
     public List<Student> sekre2;
     public List<Student> bend1;
     public List<Student> bend2;
     public List<Student> proker;
     public List<Student> asdos;
     public List<Student> aspirasi;
     public List<Student> infokom;
     public List<Student> inteks;
    public Student() {
    }

	
    public Student(int id, String name, String department, String division) {
       this.id = id;
       this.name = name;
       this.department = department;
       this.division = division;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }
    public void save(){
        Dao sdao=new Dao();
 
        sdao.addStudent(this);
        errorMessage = sdao.errorMessage;
        
     
    }
    
    public void delete(){    
        Dao sdao=new Dao();
        sdao.deleteStudent(id);
        
    }
    
    public void update(){
        Dao sdao=new Dao();
        sdao.updateStudent(this);
        
    }
    
    public String showError(){
        return errorMessage;
    }
    public void getbyid(){ 
        Dao sdao=new Dao();
        List<Student> stud=sdao.getbyID(id);
        name=stud.get(0).name;
        department=stud.get(0).department;
        division=stud.get(0).division;
    }
    
    public List<Student> getbydvs(String divisi){ 
        Dao sdao=new Dao();
        List<Student> stud=sdao.getbyDVS(divisi);
        return stud;
    }
    
    
    public List<Student> getallrecords(){
        Dao sdao=new Dao();
        List<Student> stud=sdao.retrieveStudent();
        return stud;
    }
    
    public void resetData(){
        this.id = 0;
        this.name = "";
        this.department = "";
        this.division = "";
    }
    
    public void prepareViewData(){
        
        ketua = getbydvs("Ketua");
        sekre1 = getbydvs("Sekretaris");
        sekre2 = getbydvs("Staff Sekretaris");
        bend1 = getbydvs("Bendahara");
        bend2 = getbydvs("Staff Bendahara");
        proker = getbydvs("Program Kerja");
        asdos = getbydvs("Asisten Dosen");
        aspirasi = getbydvs("Aspirasi");
        infokom = getbydvs("Informasi Komunikasi");
        inteks = getbydvs("Internal Eksternal");
    }

    public List<Student> getData(int id){
        switch(id){
            case 0:
                return ketua;
            case 1:
                return sekre1;
            case 2:
                return sekre2;
            case 3:
                return bend1;
            case 4:
                return bend2;
            case 5:
                return proker;
            case 6:
                return asdos;
            case 7:
                return aspirasi;
            case 8:
                return infokom;
            case 9:
                return inteks;
        }
        return null;
    }
}


